import type { PageServerLoad } from './$types';
import { generateFeed } from '$lib/server/feed/feed';
import { STALE_TIMER } from '$lib/server/feed/const';

/**
 * Setup ISR for the page
 * @see https://kit.svelte.dev/docs/adapter-vercel#incremental-static-regeneration
 */
export const config = {
	isr: {
		// Expiration time (in seconds) before the cached asset will be re-generated by invoking the Serverless Function.
		// Setting the value to `false` means it will never expire.
		expiration: STALE_TIMER
	}
};

/**
 * Loads necessary page data
 */
export const load = async function ({ fetch }) {
	return {
		...(await generateFeed(fetch)),
		ISR: new Date()
	};
} satisfies PageServerLoad;
