import type { PageServerLoad } from './$types';
import { generateFeed } from '$api/feed/generate';
import { STALE_TIMER } from '$api/feed/const';
import type { Feed } from '$web/components/Feed/types';

/**
 * Setup ISR for the page
 * @see https://kit.svelte.dev/docs/adapter-vercel#incremental-static-regeneration
 */
export const config = {
	isr: {
		// Expiration time (in seconds) before the cached asset will be re-generated by invoking the Serverless Function.
		// Setting the value to `false` means it will never expire.
		expiration: STALE_TIMER / 30,
	},
};

/**
 * Loads necessary page data
 */
export const load = async function ({ fetch }) {
	const feed = await generateFeed(fetch);

	return {
		...feed,
		ISR: new Date(),
	} as Feed;
} satisfies PageServerLoad;
