export const maps: { [key: string]: string } = {
	dcg_a_kalinin: 'Kalinin Airfield',
	dcg_a_runway: 'Runway',
	dcg_d_uran: 'Narva',
	dcg_d_vyazma: 'Vyazma',
	dcg_dubovka: 'Dubovka',
	dcg_f_barrikady: 'Barrikadiy Factory',
	dcg_f_bridges_of_lysovo: 'Lysovo',
	dcg_f_bykovo: 'Bykovo Factory',
	dcg_f_factory: 'Steelworks Factory',
	dcg_f_lazurnyi: 'Lazurnyi',
	dcg_glushkovo: 'Glushkovo',
	dcg_hanhijarvi: 'Hanhijarvi',
	dcg_hanhijarvi_winter: 'Hanhijarvi Winter',
	dcg_hills: 'Hills',
	dcg_hilltop: 'Hilltop',
	dcg_karvola: 'Karvola',
	dcg_karvola_winter: 'Karvola Winter',
	dcg_kirjavala: 'Kirjavala',
	dcg_kirjavala_winter: 'Kirjavala Winter',
	dcg_kirkenes_airfield: 'Kirkenes Airfield',
	dcg_kylmapuro: 'kylmapuro',
	dcg_kylmapuro_winter: 'Kylmapuro Winter',
	dcg_kymhi_airfield: 'Kymhi Airfield',
	dcg_kymhi_airfield_winter: 'Kymhi Airfield Winter',
	dcg_laisniemi: 'Laisniemi',
	dcg_laisniemi_winter: 'Laisniemi Winter',
	dcg_lakhta: 'Lakhta',
	dcg_lakhta_winter: 'Lakhta Winter',
	dcg_mannerheim: 'Mannerheim',
	dcg_mikli: 'Mikli',
	dcg_mikli_winter: 'Mikli Winter',
	dcg_narofominsk: 'Narofominsk',
	dcg_natramala: 'Natramala',
	dcg_natramala_winter: 'Natramala Winter',
	dcg_niemen: 'Neman',
	dcg_pinsk: 'Pinsk',
	dcg_puhoksen: 'Puhoksen',
	dcg_puhoksen_winter: 'Puhoksen Winter',
	dcg_radekhiv: 'Radevkiy',
	dcg_raseiniai: 'Raseiniai',
	dcg_rasputitsa: 'Rasputitsa',
	dcg_ruetzen: 'Rützen',
	dcg_rzhev: 'Rzhev',
	dcg_shiryayevo: 'Shiryayevo',
	dcg_tormasenvaara: 'Tormasenvaara',
	dcg_vainikalan: 'Vainikalan',
	dcg_vainikalan_winter: 'Vainikalan Winter',
	dcg_velikiyeluki: 'Velikiy Luki',
	dcg_olkhovatka: 'Olkhovatka',
	dcg_shaforovo: 'Shaforovo',
	dcg_wasteland: 'Wasteland',
	dcg_frozen_highlands: 'Frozen Highlands',
	dcg_black_sea_coast: 'Black Sea Coast',
	dcg_radusha_airfield: 'Radusha Airfield',
	dcg_hungarian_swamps: 'Hungarian Swamps',
	dcg_stalingrad_outskirts: 'Stalingrad Outskirts'
};
