<script lang="ts">
	export let title: string;
	export let link: string | undefined;
	export let description: string;
	export let isFirst = false;
	export let isLast = false;
	import Saos from 'saos';
</script>

<Saos animation="scale-in 0.3s cubic-bezier(0.35, 0.5, 0.65, 0.95) both" once>
	<div class="flex flex-row gap-2 md:gap-8">
		<div class="flex shrink-0 flex-col gap-2 md:ml-4">
			<div class="mx-auto w-1 grow bg-secondary-500" class:gradient-start={isFirst} />
			<div class="btn btn-icon variant-ringed-secondary">
				<i class="fas fa-code" />
			</div>
			<div class="mx-auto w-1 grow bg-secondary-500" class:gradient-end={isLast} />
		</div>
		<div class="grow py-8">
			<div class="flex flex-col gap-4">
				<h3>
					{#if link}
						<a href={link} target="_blank" rel="noopener noreferrer">
							{title}
						</a>
					{:else}
						{title}
					{/if}
				</h3>
				<p>
					{description}
				</p>
			</div>
		</div>
	</div>
</Saos>

<style lang="postcss">
	.gradient-start {
		background: linear-gradient(to top, theme(colors.secondary.500), rgba(255, 0, 0, 0));
	}
	.gradient-end {
		background: linear-gradient(to bottom, theme(colors.secondary.500), rgba(255, 0, 0, 0));
	}

	/* ----------------------------------------------
	* Generated by Animista on 2023-5-9 22:57:1
	* Licensed under FreeBSD License.
	* See http://animista.net/license for more info. 
	* w: http://animista.net, t: @cssanimista
	* ---------------------------------------------- */
	@-webkit-keyframes -global-scale-in {
		0% {
			-webkit-transform: scale(0.75);
			transform: scale(0.75);
		}
		100% {
			-webkit-transform: scale(1);
			transform: scale(1);
		}
	}
	@keyframes -global-scale-in {
		0% {
			-webkit-transform: scale(0.75);
			transform: scale(0.75);
		}
		100% {
			-webkit-transform: scale(1);
			transform: scale(1);
		}
	}
</style>
